version: '2'
services:
    mssql:
        image: "microsoft/mssql-server-linux"
        volumes:
            - /mnt/content/Videos/Progz/B/mssql1:/var/opt
        environment:
            - SA_PASSWORD
            - ACCEPT_EULA=Y
        ports:
            - "1433:1433"
    weba:
        image: "chaosengine/dotnetplayground:latest"
        expose:
            - "5000"
        volumes:
            - ./shared:/shared
        environment:
            - ConnectionStrings__SqlServer
            - ConnectionStrings__MySQL
        depends_on:
            - mssql
        links:
            - mssql
    webb:
        image: "chaosengine/dotnetplayground:latest"
        expose:
            - "5000"
        volumes:
            - ./shared:/shared
        environment:
            - ConnectionStrings__SqlServer
            - ConnectionStrings__MySQL
        depends_on:
            - mssql
        links:
            - mssql
    webc:
        image: "chaosengine/dotnetplayground:latest"
        expose:
            - "5000"
        volumes:
            - ./shared:/shared
        environment:
            - ConnectionStrings__SqlServer
            - ConnectionStrings__MySQL
        depends_on:
            - mssql
        links:
            - mssql
    haproxy:
        image: haproxy
        volumes:
            - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
            - ./sockets:/sockets
        links:
            - weba
            - webb
            - webc
        ports:
            - "70:70"
